import 'dart:ui';

import 'package:get/get_navigation/src/root/internacionalization.dart';

class LocalString extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    //ENGLISH LANGUAGE
    'en_US':{
      'oops':'Oops!',
      'something_went_wrong':'Something went wrong.',
      'technofino_community':'TechnofinoCommunity',
      'post_thread_in_forum':'Post thread in forum...',
      'discussions':'Discussions',
      'messages':'Messages',
      'cancel':'Cancel',
      'create_new_thread':'Create new thread',
      "title":'Title',
      "message":'Message',
      'you_must_log_in_to_perform_this_action':'You must log-in to perform this action.',
      'notifications':'Notifications',
      'no_alerts_found':'No alerts found!',
      'log_in':'Log in',
      'account':'Account',
      'account_details':'Account details',
      'change_username':'Change username',
      'conversations':'Conversations',
      'following_people':'Following people',
      'ignoring_people':'Ignoring people',
      'watched_threads':'Watched threads',
      'language':'Language',
      'appearance':'Appearance',
      'dark_mode':'Dark Mode',
      'off':'Off',
      'on':'On',
      'rate_us_on_store':'Rate us on Store',
      'open_links_in':'Open Links in',
      'in_app_chrome':'In-app Chrome',
      'terms_and_rules':'Terms and rules',
      'privacy_policy':'Privacy policy',
      'log_out':'Log out',
      'app_version':'App version',
      'follow':"Follow",
      'comment':'Comment',
      'share':'Share',
      'are_you_sure_you_want_to_discard_changes':'Are you sure you want to discard changes?',
      'ok':'Ok',
      'post_reply':'Post Reply',
      'photo':'Photo',
      'take_photo':'Take photo',
      'file':'File',
      'sending':'Sending',
      'post':'Post',
      'delete':'Delete',
      'reply':'Reply',
      'report':'Report',
      'open_in_browser':'Open in browser',
      'no_conversation_found':'No Conversations found!',
      'expanded_editor':'Expanded editor',
      'write_a_comment':'Write a comment...',
      'like':'Like',
      'angry':'Angry',
      'sad':'Sad',
      'wow':'Wow',
      'love':'Love',
      'username':'Username',
      'change_reason':'Change reason',
      'please_explain_the_reason_for_this_username_change':'Please explain the reason for this username change',
      'save':'Save',
      'loading':'Loading',
      'update_your_status':'Update your status',
      'joined':'Joined',
      'reaction_score':'Reaction score',
      'trophy_points':'Trophy points',
      'location':'Location',
      'facebook':'Facebook',
      'twitter':'Twitter',
      'write_something':'Write something',
      'about':'About',
      'threads':'Threads',
      'profile_posts':'Profile posts',
      'block_user':'Block user',
      'update_avatar':'Update avatar',
      'choose_from_gallery':'Choose from gallery',
      'no_threads_found':'No threads found!',
      'views':'views',
      'replies':'replies',
      'email_required':'Email required',
      'username_or_email':'Username or Email',
      'password_required':'Password required',
      'email':'Email',
      'password':'Password',
      'sign_in_with_google':'Sign in with Google',
      'sign_in_with_twitter':'Sign in with Twitter',
      'register_new_account':'Register new account',
      'report_content':'Report content',


    },
    //Polish LANGUAGE
    'pl':{
      'oops':'Ups!',
      'something_went_wrong':'Coś poszło nie tak.',
      'technofino_community':'Społeczność Technofino',
      'post_thread_in_forum':'Opublikuj wątek na forum...',
      'discussions':'Dyskusje',
      'messages':'Wiadomości',
      'cancel':'Anulować',
      'create_new_thread':'Utwórz nowy wątek',
      "title":'Tytuł',
      "message":'Wiadomość',
      'you_must_log_in_to_perform_this_action':'Musisz się zalogować, aby wykonać tę akcję.',
      'notifications':'Powiadomienia',
      'no_alerts_found':'Nie znaleziono alertów!',
      'log_in':'Zaloguj sie',
      'account':'Rachunek',
      'account_details':'Szczegóły Konta',
      'change_username':'Zmień nazwę użytkownika',
      'conversations':'Rozmowy',
      'following_people':'Following people',
      'ignoring_people':'Ignorowanie ludzi',
      'watched_threads':'Obserwowane wątki',
      'language':'język',
      'appearance':'Wygląd zewnętrzny',
      'dark_mode':'Tryb ciemny',
      'off':'Wyłączony',
      'on':'na',
      'rate_us_on_store':'Oceń nas w sklepie',
      'open_links_in':'Otwórz linki w',
      'in_app_chrome':'In-app Chrome',
      'terms_and_rules':'Warunki i zasady',
      'privacy_policy':'Polityka prywatności',
      'log_out':'Wyloguj',
      'app_version':'Wersja aplikacji',
      'follow':"Podążać",
      'comment':'Komentarz',
      'share':'Dzielić',
      'are_you_sure_you_want_to_discard_changes':'Czy na pewno chcesz odrzucić zmiany?',
      'ok':'Ok',
      'post_reply':'Odpowiedź na post',
      'photo':'Zdjęcie',
      'take_photo':'Zrobić zdjęcie',
      'file':'Plik',
      'sending':'Sending',
      'post':'Poczta',
      'delete':'Usuwać',
      'reply':'Reply',
      'report':'Raport',
      'open_in_browser':'Otwórz w przeglądarce',
      'no_conversation_found':'Nie znaleziono rozmów!',
      'expanded_editor':'Rozszerzony edytor',
      'write_a_comment':'Napisz komentarz...',
      'like':'Like',
      'angry':'Angry',
      'sad':'Smutny',
      'wow':'Wow',
      'love':'Miłość',
      'username':'Nazwa użytkownika',
      'change_reason':'Zmień powód',
      'please_explain_the_reason_for_this_username_change':'Wyjaśnij powód zmiany nazwy użytkownika',
      'save':'Save',
      'loading':'Ładowanie',
      'update_your_status':'Zaktualizuj swój status',
      'joined':'Dołączył',
      'reaction_score':'Wynik reakcji',
      'trophy_points':'Punkty trofeum',
      'location':'Lokalizacja',
      'facebook':'Facebook',
      'twitter':'Twitter',
      'write_something':'Write something',
      'about':'O',
      'threads':'Wątki',
      'profile_posts':'Posty w profilu',
      'block_user':'Zablokować użytkownika',
      'update_avatar':'Zaktualizuj awatar',
      'choose_from_gallery':'Wybierz z galerii',
      'no_threads_found':'Nie znaleziono wątków!',
      'views':'wyświetlenia',
      'replies':'odpowiedzi',
      'email_required':'Email wymagany',
      'username_or_email':'Nazwa użytkownika lub Email',
      'password_required':'wymagane hasło',
      'email':'E-mail',
      'password':'Hasło',
      'sign_in_with_google':'Zaloguj się przez Google',
      'sign_in_with_twitter':'Zaloguj się przez Twitter',
      'register_new_account':'Zarejestruj Nowe Konto',
      'report_content':'Treść raportu',
    },
    //Vietnames LANGUAGE
    'vi':{
      'oops':'Rất tiếc!',
      'something_went_wrong':'Đã xảy ra sự cố.',
      'technofino_community':'TechnofinoCommunity',
      'post_thread_in_forum':'Đăng chủ đề trong diễn đàn...',
      'discussions':'Thảo luận',
      'messages':'Tin nhắn',
      'cancel':'Hủy bỏ',
      'create_new_thread':'Tạo chuỗi mới',
      'post':'Bưu kiện',
      "title":'Tiêu đề',
      "message":'Thông điệp',
      'you_must_log_in_to_perform_this_action':'Bạn phải đăng nhập để thực hiện hành động này.',
      'notifications':'Thông báo',
      'no_alerts_found':'Không tìm thấy cảnh báo!',
      'log_in':'Đăng nhập',
      'account':'Tài khoản',
      'account_details':'Chi tiết tài khoản',
      'change_username':'Thay đổi tên người dùng',
      'conversations':'Cuộc trò chuyện',
      'following_people':'Những người sau đây',
      'ignoring_people':'Phớt lờ mọi người',
      'watched_threads':'Chủ đề đã xem',
      'language':'Ngôn ngữ',
      'appearance':'Vẻ bề ngoài',
      'dark_mode':'Chế độ tối',
      'off':'Tắt',
      'on':'trên',
      'rate_us_on_store':'Đánh giá chúng tôi trên Store',
      'open_links_in':'Mở liên kết trong',
      'in_app_chrome':'In-app Chrome',
      'terms_and_rules':'Điều khoản và quy tắc',
      'privacy_policy':'Chính sách bảo mật',
      'log_out':'Đăng xuất',
      'app_version':'Phiên bản ứng dụng',
      'follow':"Theo dõi",
      'comment':'Bình luận',
      'share':'Share',
      'are_you_sure_you_want_to_discard_changes':'Bạn có chắc chắn muốn hủy các thay đổi không?',
      'ok':'Vâng',
      'post_reply':'Bài trả lời',
      'photo':'ảnh',
      'take_photo':'Chụp hình',
      'file':'Tập tin',
      'sending':'Sending',
      'delete':'Xóa bỏ',
      'reply':'Đáp lại',
      'report':'Báo cáo',
      'open_in_browser':'Mở trong trình duyệt',
      'no_conversation_found':'Không tìm thấy cuộc trò chuyện nào!',
      'expanded_editor':'Trình chỉnh sửa mở rộng',
      'write_a_comment':'Viết bình luận...',
      'like':'Giống',
      'angry':'Tức giận',
      'sad':'Buồn',
      'wow':'Wow',
      'love':'Yêu',
      'username':'tên tài khoản',
      'change_reason':'Thay đổi lý do',
      'please_explain_the_reason_for_this_username_change':'Vui lòng giải thích lý do thay đổi tên người dùng này',
      'save':'Tiết kiệm',
      'loading':'Đang tải',
      'update_your_status':'cập nhật trạng thái của bạn',
      'joined':'Đã tham gia',
      'reaction_score':'Điểm phản ứng',
      'trophy_points':'Điểm danh hiệu',
      'location':'Địa điểm',
      'facebook':'Facebook',
      'twitter':'Twitter',
      'write_something':'Viết vài thứ',
      'about':'Về',
      'threads':'Chủ đề',
      'profile_posts':'Bài đăng hồ sơ',
      'block_user':'Chặn người dùng',
      'update_avatar':'Cập nhật hình đại diện',
      'choose_from_gallery':'Chọn từ phòng trưng bày',
      'no_threads_found':'Không có chủ đề tìm!',
      'views':'lượt xem',
      'replies':'trả lời',
      'email_required':'Email bắt buộc',
      'username_or_email':'Tên người dùng hoặc email',
      'password_required':'mật khẩu được yêu câu',
      'email':'E-mail',
      'password':'Mật khẩu',
      'sign_in_with_google':'Đăng nhập bằng Google',
      'sign_in_with_twitter':'Đăng nhập bằng Twitter',
      'register_new_account':'Đăng ký tài khoản mới',
      'report_content':'Báo cáo nội dung',
    },
    //Russian LANGUAGE
    'ru':{
      'oops':'Упс!',
      'something_went_wrong':'Что-то пошло не так.',
      'technofino_community':'ТехнофиноСообщество',
      'post_thread_in_forum':'Разместить тему на форуме...',
      'discussions':'Обсуждения',
      'messages':'Сообщения',
      'cancel':'Отмена',
      'create_new_thread':'Создать новую тему',
      "title":'Заголовок',
      "message":'Сообщение',
      'you_must_log_in_to_perform_this_action':'Вы должны войти в систему, чтобы выполнить это действие.',
      'notifications':'Уведомления',
      'no_alerts_found':'Оповещения не найдены!',
      'log_in':'Авторизоваться',
      'account':'Счет',
      'account_details':'Детали учетной записи',
      'change_username':'Изменение имени пользователя',
      'conversations':'Разговоры',
      'following_people':'Следующий люди',
      'ignoring_people':'Игнорирование людей',
      'watched_threads':'Просмотренные темы',
      'language':'Язык',
      'appearance':'вид',
      'dark_mode':'Темный режим',
      'off':'Выключенный',
      'on':'на',
      'rate_us_on_store':'Оцените нас в магазине',
      'open_links_in':'Открыть ссылки в',
      'in_app_chrome':'В приложении Chrome',
      'terms_and_rules':'Условия и правила',
      'privacy_policy':'Политика конфиденциальности',
      'log_out':'Выйти',
      'app_version':'Версия приложения',
      'follow':"Следовать",
      'comment':'Комментарий',
      'share':'Делиться',
      'are_you_sure_you_want_to_discard_changes':'Вы уверены, что хотите отменить изменения??',
      'ok':'Ok',
      'post_reply':'Ответить',
      'photo':'Фото',
      'take_photo':'Брать Фото',
      'file':'Файл',
      'sending':'Отправка',
      'post':'Почта',
      'delete':'Удалить',
      'reply':'Отвечать',
      'report':'Отчет',
      'open_in_browser':'Открыть в браузере',
      'no_conversation_found':'Беседы не найдены!',
      'expanded_editor':'Расширенный редактор',
      'write_a_comment':'Написать комментарий...',
      'like':'Нравиться',
      'angry':'Злой',
      'sad':'Грустный',
      'wow':'Wow',
      'love':'Любовь',
      'username':'Имя пользователя',
      'change_reason':'Причина изменения',
      'please_explain_the_reason_for_this_username_change':'Пожалуйста, объясните причину изменения имени пользователя',
      'save':'Сохранять',
      'loading':'Загрузка',
      'update_your_status':'Обновите свой статус',
      'joined':'Присоединился',
      'reaction_score':'Оценка реакции',
      'trophy_points':'Трофейные очки',
      'location':'Расположение',
      'facebook':'Фейсбук',
      'twitter':'Твиттер',
      'write_something':'Напиши что-нибудь',
      'about':'About',
      'threads':'Threads',
      'profile_posts':'Сообщения профиля',
      'block_user':'Блокировать пользователя',
      'update_avatar':'Обновить аватар',
      'choose_from_gallery':'Выбрать из галереи',
      'no_threads_found':'Темы не найдены!',
      'views':'Просмотры',
      'replies':'ответы',
      'email_required':'Электронная почта требуется',
      'username_or_email':'Имя пользователя или адрес электронной почты',
      'password_required':'Требуется пароль',
      'email':'Эл. адрес',
      'password':'Пароль',
      'sign_in_with_google':'Войти через Google',
      'sign_in_with_twitter':'Войти через Твиттер',
      'register_new_account':'Зарегистрировать новую учетную запись',
      'report_content':'Содержание отчета',
    }
  };


  static Map<String,Locale> locale={
    "English":Locale('en','US'),
    "Polish":Locale('pl',''),
    "Vietnamese":Locale('vi',''),
    "Russian":Locale('ru',''),
  };
}