name: technofino
description: TechnoFino Community

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  retrofit: ^3.0.1+1
  json_annotation: ^4.6.0
  dio: ^4.0.6
  freezed_annotation: ^2.0.3
  http: ^0.13.4
  provider: ^6.0.3
  intl: ^0.17.0
  flutter_html: ^2.2.1
  photo_view: ^0.14.0
  modal_bottom_sheet: ^2.1.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  permission_handler: ^9.2.0
  image_cropper: ^2.0.3
  file_picker: ^4.6.1
  badges: ^2.0.3
  google_sign_in: ^5.4.0
  url_launcher: ^6.1.5
  webview_flutter: any
  twitter_login: ^4.2.3
  get: ^4.6.5
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^2.3.6
  flutter_slidable: ^2.0.0
  share_plus: ^4.0.10+1
  flutter_branch_sdk: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.11
  built_value_generator: ^8.3.2
  freezed: ^2.0.3+1
  json_serializable: any
  flutter_launcher_icons: ^0.10.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
dependency_overrides:
  analyzer: 4.2.0
  dart_style: any
  gql: 0.13.0
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/technofino.png
    - assets/icons/google.png
    - assets/icons/filter.png
    - assets/icons/ribbon.png
    - assets/icons/edit_post.png
    - assets/icons/angry_icon.png
    - assets/icons/haha_icon.png
    - assets/icons/sad_icon.png
    - assets/icons/wow_icon.png
    - assets/icons/love_icon.png
    - assets/icons/options.png
    - assets/icons/twitter.png
    - assets/icons/alert_icon.png
    - assets/icons/youtube_icon.png
    - assets/icons/email.png
    - assets/icons/toolbar.png
    - assets/icons/technofino_nodes_icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/NotoEmoji-VariableFont_wght.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/technofino_nodes_icons/technofino_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21